#!/usr/bin/env Rscript

# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2024-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

# Curate sample-level phenotype data for HMF
# Note that HMF phenotype data must be preprocessed with curate_hmf_manifests.py


#########
# Setup #
#########
# Load necessary libraries and constants
options(scipen=1000, stringsAsFactors=F)
require(argparse, quietly=TRUE)
require(G2CR, quietly=TRUE)
G2CR::load.constants("all")

# Declare constants used in variable parsing
loc.map <- c("cup" = "unknown primary",
             "unknown primary (e.g. cup)" = "unknown primary",
             "NA" = "unknown")
type.map <- c("NA" = "cancer",
              "unknown" = "cancer",
              "other" = "cancer")


##################
# Data Functions #
##################
# Load deduplicated manifest .tsv generated by curate_hmf_manifests.py
load.manifest <- function(tsv.in){
  # Read file
  df <- read.table(tsv.in, header=T, sep="\t")

  # Drop file path columns
  fp.cols <- c("tumor_cram", "tumor_crai", "normal_cram", "normal_crai",
               "germline_vcf", "germline_vcf_idx")
  df[, intersect(colnames(df), fp.cols)] <- NULL

  # Clean simple columns
  df$Sample <- df$hmfPatientId
  df$Cohort <- "hmf"
  df$reported_sex <- df$gender
  df$reported_race_or_ethnicity <- NA
  df$birth_year <- as.numeric(df$birthYear)
  df$bmi <- df$height <- df$weight <- NA
  df$stage <- "IV"
  df$metastatic <- 1
  df$grade <- "unknown"
  df$smoking_history <- NA
  df$cancer_icd10 <- NA
  df$wgs_tissue <- "blood"

  # Clean age data s/t no reported date is before reported birth year
  # (This happens only once in our manifest, with one breast cancer patient
  # being coded as tamoxifen end date 1900-01-01 but born in 1927)
  date.cols <- c("deathDate", "biopsyDate", "treatmentStartDate",
                 "treatmentEndDate", "responseDate")
  df[, date.cols] <- apply(df[, c("birth_year", date.cols)], 1, function(v){
    b.y <- as.numeric(v[1])
    target.v <- unlist(as.character(v[-1]))
    other.y <- sapply(target.v, function(y){
      as.numeric(unlist(strsplit(y, split="-", fixed=T))[1])
    })
    miscode.idx <- which(other.y < b.y)
    target.v[miscode.idx] <- NA
    return(target.v)
  })

  # Compute earliest reported age post-diagnosis, which we interpret as index time
  df$d.b <- as.Date(paste(df$birthYear, "01-01", sep="-"))
  df$d.dx <- as.Date(apply(df[, date.cols], 1, function(d){min(as.Date(d), na.rm=T)}))
  df$age <- as.numeric((df$d.dx - df$d.b) / 365)
  df$age[which(is.infinite(df$age))] <- NA

  # Infer survival info
  has.fu.idx <- which(apply(df[, date.cols], 1, function(d){any(!is.na(d))}))
  df$d.lc <- as.Date(apply(df[, date.cols], 1, function(d){max(as.Date(d), na.rm=T)}))
  df$years_to_last_contact <- as.numeric(df$d.lc - as.Date(df$d.dx)) / 365
  df$years_to_last_contact[which(df$years_to_last_contact <= 0)] <- NA
  has.fu.idx <- intersect(has.fu.idx, which(df$years_to_last_contact > 0))
  df$age_at_last_contact <- df$age + df$years_to_last_contact
  df$age_at_last_contact[-has.fu.idx] <- df$age[-has.fu.idx]
  df$years_left_censored <- NA
  df$years_left_censored[has.fu.idx] <- 0
  df$vital_status <- NA
  df$vital_status[has.fu.idx] <- 1
  died.idx <- which(!is.na(df$deathDate))
  df$vital_status[died.idx] <- 0

  # Clean other cancer diagnosis information
  dx.cols <- c("primaryTumorLocation", "primaryTumorSubLocation",
               "primaryTumorType", "primaryTumorSubType")
  df$original_dx <- apply(df[, dx.cols], 1, function(v){
    v <- tolower(as.character(v))
    loc <- remap(if(is.na(v[2])){v[1]}else{v[2]}, loc.map)
    type <- remap(if(grepl("cancer|carcinoma", v[4])){v[4]}else{v[3]}, type.map)
    gsub("[ ]+", "_", paste(loc, type))
  })

  return(df)
}

# Map HMF cancer information onto simplified G2C cancer classification scheme
add.cancer.labels <- function(df, tsv.in){
  # Read cancer type map
  class.table <- read.table(tsv.in, header=T, sep="\t")
  class.table$cancer <- gsub(" ", "_", tolower(class.table$class))
  bad.class.idx <- which(!class.table$cancer %in% names(cancer.names))
  class.table$cancer[bad.class.idx] <- "other"
  class.table$class <- NA

  # Left outer join to keep all rows in df
  merge(df, class.table, all.x=T, all.y=F)
}


###########
# RScript #
###########
# Parse command line arguments and options
parser <- ArgumentParser(description="Curate HMF phenotype data")
parser$add_argument("--preprocessed-tsv", metavar=".tsv", type="character", required=TRUE,
                    help=paste("combined_metadata_and_manifest.unique_patients.tsv.gz",
                               "generated by curate_hmf_manifests.py"))
parser$add_argument("--cancer-classification-tsv", metavar=".tsv", type="character",
                    help=paste("Cancer type classification table as",
                               "supplied to curate_hmf_manifests.py"),
                    required=TRUE)
parser$add_argument("--out-tsv", metavar=".tsv", type="character", required=TRUE,
                    help="path to output.tsv")
args <- parser$parse_args()

# # DEV:
# args <- list("preprocessed_tsv" = "~/Desktop/Collins/VanAllen/pancancer_wgs/data_and_cohorts/hmf/hmf-dr-355/HMF.combined_metadata_and_manifest.unique_patients.tsv.gz",
#              "cancer_classification_tsv" = "~/Desktop/Collins/VanAllen/pancancer_wgs/data_and_cohorts/hmf/hmf-dr-355/hmf-dr-355.g2c_classification_scheme.tsv",
#              "out_tsv" = "~/scratch/hmf.pheno.dev.tsv")

# Load preprocessed sample manifest
df <- load.manifest(args$preprocessed_tsv)

# Map cancer label
df <- add.cancer.labels(df, args$cancer_classification_tsv)

# Write to --out-tsv
col.order <- c("Sample", "Cohort", "reported_sex", "reported_race_or_ethnicity",
               "age", "birth_year", "vital_status", "age_at_last_contact",
               "years_to_last_contact", "years_left_censored", "height",
               "weight", "bmi", "cancer", "stage", "metastatic", "grade",
               "smoking_history", "cancer_icd10", "original_dx", "wgs_tissue")
write.table(df[!is.na(df$Sample), col.order], args$out_tsv, col.names=T,
            row.names=F, sep="\t", quote=F)
