#!/usr/bin/env Rscript

# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2024-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

# Curate sample-level phenotype data for HGSVC/1000G

# Note: requires HGSV_metadata.DFCI_G2C_selected.tsv as input,
# which is generated by select_hgsv_samples.R (script is local, not in git)


#########
# Setup #
#########
# Load necessary libraries and constants
options(scipen=1000, stringsAsFactors=F)
require(argparse, quietly=TRUE)
require(G2CR, quietly=TRUE)
G2CR::load.constants("all")

# Declare constants used in variable parsing
pop.map <- c("AFR" = "african",
             "AMR" = "american",
             "EAS" = "east_asian",
             "EUR" = "european",
             "SAS" = "south_asian")


##################
# Data Functions #
##################
# Load and clean data from HGSV_metadata.DFCI_G2C_selected.tsv
load.meta <- function(tsv.in){
  # Read file
  df.all <- read.table(tsv.in, header=T, sep="\t", quote="")

  # Only keep relevant columns
  df <- df.all[, c("library_name", "Sex", "Superpopulation.code")]

  # Clean basic columns
  df$Sample <- df$library_name
  df$Cohort <- "hgsvc"
  df$reported_sex <- tolower(df$Sex)
  df$reported_race_or_ethnicity <- remap(df$Superpopulation.code, pop.map)
  df$cancer <- "unknown"
  df$wgs_tissue <- "lymphoblastoid_cell_line"
  na.cols <- c("age", "birth_year", "vital_status", "age_at_last_contact",
               "years_to_last_contact", "years_left_censored", "height",
               "weight", "bmi", "stage", "metastatic", "grade",
               "smoking_history", "cancer_icd10", "original_dx")
  df[, na.cols] <- NA

  return(df)
}


###########
# RScript #
###########
# Parse command line arguments and options
parser <- ArgumentParser(description="Curate HGSVC phenotype data")
parser$add_argument("--metadata-tsv", metavar=".tsv", type="character", required=TRUE,
                    help=paste("HGSV_metadata.DFCI_G2C_selected.tsv generated by",
                               "select_hgsv_samples.R"))
parser$add_argument("--out-tsv", metavar=".tsv", type="character", required=TRUE,
                    help="path to output.tsv")
args <- parser$parse_args()

# # DEV:
# args <- list("metadata_tsv" = "~/Desktop/Collins/VanAllen/pancancer_wgs/data_and_cohorts/hgsvc/HGSV_metadata.DFCI_G2C_selected.tsv",
#              "out_tsv" = "~/scratch/hgsvc.pheno.dev.tsv")

# Load and clean metadata
df <- load.meta(args$metadata_tsv)

# Write to --out-tsv
col.order <- c("Sample", "Cohort", "reported_sex", "reported_race_or_ethnicity",
               "age", "birth_year", "vital_status", "age_at_last_contact",
               "years_to_last_contact", "years_left_censored", "height",
               "weight", "bmi", "cancer", "stage", "metastatic", "grade",
               "smoking_history", "cancer_icd10", "original_dx", "wgs_tissue")
write.table(df[, col.order], args$out_tsv, col.names=T,
            row.names=F, sep="\t", quote=F)
