#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2025-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

"""
Parse a site benchmarking .json of plotting inputs as generated by PrepSiteBenchDataToPlot.wdl
"""

import json
import sys

infile = sys.argv[1]
with open(infile, "r") as f:
  data = json.load(f)

def write_array(name, val):
  val = [v for v in val if v is not None and v != ""]
  if len(val) == 0:
    return
  with open(f"{name}.txt", "w") as out:
      for item in (val or []):
          if item is not None:
              out.write(item + "\n")

write_array("snv_ppv_beds", data.get("snv_ppv_beds", []) + [data.get("snv_ppv_union")])
write_array("indel_ppv_beds", data.get("indel_ppv_beds", []) + [data.get("indel_ppv_union")])
write_array("sv_ppv_beds", data.get("sv_ppv_beds", []) + [data.get("sv_ppv_union")])

write_array("ppv_by_af", data.get("ppv_by_af"))
write_array("sens_by_af", data.get("sens_by_af"))

