#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2025-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

"""
Concatenates one or more sample genotype map files generated by clean_sample_genotypes.py
Splits the concatenated output into one file per sample
"""


import gzip
import sys


def process_file(tsv_in, outdir):
    """
    Reads through a single input .tsv and appends the contents to sample files
    """

    out_handles = {}
    
    with gzip.open(tsv_in, 'rt') as f:
    
        for line in f:
            sid, vid, gt = line.rstrip().split('\t')
    
            outfile = '{}/{}.gt.tsv.gz'.format(outdir, sid)
            if sid not in out_handles.keys():
                out_handles[sid] = gzip.open(outfile, 'at', encoding='utf-8')
    
            fout = out_handles[sid]
            fout.write('\t'.join([vid, gt]) + '\n')
    
    for handle in out_handles.values():
        handle.close()


def main():
    infile_list = sys.argv[1]
    outdir = sys.argv[2]

    with open(infile_list) as lin:
    	input_files = [f.rstrip() for f in lin.readlines()]
    
    for tsv_file in input_files:
        process_file(tsv_file, outdir)


if __name__ == "__main__":
    main()

