# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2023-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

# Reheaders & reblocks a gVCF generated by GATK-HC
# Simply a combination of ReheaderGvcf.wdl and ReblockGvcf.wdl for convenience


version 1.0


import "https://raw.githubusercontent.com/vanallenlab/pancan_germline_wgs/main/wdl/ReheaderGvcf.wdl" as Reheader
import "https://raw.githubusercontent.com/vanallenlab/pancan_germline_wgs/main/wdl/ReblockGvcf.wdl" as Reblock


workflow PostprocessGvcf {
  input {
    File input_gvcf
    File input_gvcf_index
    String sample_name
    File ref_fasta
    File ref_fai
    File ref_dict
    String gatk_docker = "us.gcr.io/broad-gatk/gatk:4.4.0.0"
    String bcftools_docker
  }

  call Reheader.Reheader as Step1 {
    input:
      input_gvcf = input_gvcf,
      sample_name = sample_name,
      bgzip_compression = 2,
      docker = bcftools_docker
  }

  call Reblock.GnarlyReblock as Step2 {
    input:
      gvcf = Step1.gvcf_out,
      gvcf_idx = Step1.gvcf_out_idx,
      ref_fasta = ref_fasta,
      ref_fai = ref_fai,
      ref_dict = ref_dict,
      out_fname = sample_name + ".reblocked.g.vcf.gz",
      docker = gatk_docker
  }
  
  output {
    File final_gvcf = Step2.output_gvcf
    File final_gvcf_idx = Step2.output_gvcf_idx
  }
}

