#!/usr/bin/env bash

# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2023-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

# Helper bash functions for All of Us Researcher Workbench

# Check sample status for one cancer type and a single workflow (gatk-hc, gatk-sv, or gcnv-pp)
check_status() {
  if [ $# -ne 2 ]; then
    echo "Must specify (gatk-hc|gatk-sv|gvcf-pp) and cancer type as first two positional arguments"
  else
    wflow=$1
    cancer=$2
  fi
  status_tsv=~/cromshell/progress/$cancer.$( echo $wflow | sed 's/-/_/g' ).sample_progress.tsv
  if [ -e $status_tsv ]; then
    n=$( cat ~/sample_lists/$cancer.samples.list | wc -l )
    k=0
    while read sid cram crai; do
      ((k++))
      echo -e "Checking $sid; sample $k of $n $cancer patients"
      ~/code/scripts/check_aou_gatk_status.py \
        --sample-id "$sid" \
        --mode $wflow \
        --bucket $WORKSPACE_BUCKET \
        --staging-bucket $MAIN_WORKSPACE_BUCKET \
        --status-tsv $status_tsv \
        --update-status \
        --unsafe \
        --always-print-status-to-stdout
    done < ~/data/cram_paths/$cancer.cram_paths.tsv
  fi
}

# Update status table of sample progress
update_status_table() {
  if [ $# -ne 1 ]; then
    echo "Must specify (gatk-hc|gatk-sv|gvcf-pp) as first positional argument"
  else
    wflow=$1
  fi
  while read cancer; do
    awk -v cancer=$cancer -v wflow=$wflow \
      '{ if ($1!=cancer || $2!=wflow) print $0 }' \
      ~/cromshell/progress/gatk.sample_progress.summary.tsv \
    > ~/cromshell/progress/gatk.sample_progress.summary.tsv2
    cut -f2 \
      ~/cromshell/progress/$cancer.$( echo $wflow | sed 's/-/_/g' ).sample_progress.tsv \
    | sort | uniq -c | sort -nrk1,1 \
    | awk -v cancer=$cancer -v wflow=$wflow -v OFS="\t" \
      '{ print cancer, wflow, $2, $1 }' \
    >> ~/cromshell/progress/gatk.sample_progress.summary.tsv2
    mv \
      ~/cromshell/progress/gatk.sample_progress.summary.tsv2 \
      ~/cromshell/progress/gatk.sample_progress.summary.tsv
  done < ~/cancers.list
  sort -Vk1,3 ~/cromshell/progress/gatk.sample_progress.summary.tsv
}

# Clean up intermediate files generated by Cromwell
cleanup_garbage() {
  dt_fmt=$( date '+%m_%d_%Y.%Hh%Mm%Ss' )
  garbage_uri="$WORKSPACE_BUCKET/dumpster/dfci_g2c.aou_rw.$dt_fmt.garbage"
  gsutil -m cp ~/uris_to_delete.list $garbage_uri
  rm ~/uris_to_delete.list
  echo -e "{\"DeleteGcpObjects.uri_list\": \"$garbage_uri\"}" \
  > ~/cromshell/inputs/empty_dumpster.$dt_fmt.inputs.json
  cromshell --no_turtle -t 120 -mc submit \
    --options-json ~/code/refs/json/aou.cromwell_options.default.json \
    ~/code/wdl/pancan_germline_wgs/DeleteGcpObjects.wdl \
    ~/cromshell/inputs/empty_dumpster.$dt_fmt.inputs.json \
  | jq .id | tr -d '"' \
  >> ~/cromshell/job_ids/empty_dumpster.job_ids.list
}
