#!/usr/bin/env bash

# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2023-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

# Helper bash functions for All of Us Researcher Workbench

# Clean up intermediate files generated by Cromwell
cleanup_garbage() {
  dt_fmt=$( date '+%m_%d_%Y.%Hh%Mm%Ss' )
  garbage_uri="$WORKSPACE_BUCKET/dumpster/dfci_g2c.aou_rw.$dt_fmt.garbage"
  gsutil -m cp uris_to_delete.list $garbage_uri
  rm uris_to_delete.list
  echo -e "{\"DeleteGcpObjects.uri_list\": \"$garbage_uri\"}" \
  > cromshell/inputs/empty_dumpster.$dt_fmt.inputs.json
  cromshell-alpha submit \
    --options-json code/refs/json/aou.cromwell_options.default.json \
    code/wdl/code/wdl/pancan_germline_wgs/DeleteGcpObjects.wdl \
    cromshell/inputs/empty_dumpster.$dt_fmt.inputs.json \
  | tail -n4 | jq .id | tr -d '"' \
  >> cromshell/job_ids/empty_dumpster.job_ids.list
}

